# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 498)
        self.pushButton_OPEN = QtWidgets.QPushButton(Form)
        self.pushButton_OPEN.setGeometry(QtCore.QRect(430, 30, 75, 23))
        self.pushButton_OPEN.setObjectName("pushButton_OPEN")
        self.dial = QtWidgets.QDial(Form)
        self.dial.setGeometry(QtCore.QRect(110, 160, 61, 81))
        self.dial.setObjectName("dial")
        self.dial_2 = QtWidgets.QDial(Form)
        self.dial_2.setGeometry(QtCore.QRect(200, 160, 61, 81))
        self.dial_2.setObjectName("dial_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(350, 30, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 240, 54, 12))
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_OPEN.setText(_translate("Form", "打开串口"))
        self.label.setText(_translate("Form", "-----------"))
