# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(641, 498)
        self.pushButton_OPEN = QtWidgets.QPushButton(Form)
        self.pushButton_OPEN.setGeometry(QtCore.QRect(430, 30, 75, 23))
        self.pushButton_OPEN.setObjectName("pushButton_OPEN")
        self.dial = QtWidgets.QDial(Form)
        self.dial.setGeometry(QtCore.QRect(110, 160, 61, 81))
        self.dial.setObjectName("dial")
        self.dial_2 = QtWidgets.QDial(Form)
        self.dial_2.setGeometry(QtCore.QRect(200, 160, 61, 81))
        self.dial_2.setObjectName("dial_2")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setGeometry(QtCore.QRect(350, 30, 69, 22))
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(520, 170, 51, 23))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit_PWM = QtWidgets.QLineEdit(Form)
        self.lineEdit_PWM.setGeometry(QtCore.QRect(520, 140, 51, 20))
        self.lineEdit_PWM.setObjectName("lineEdit_PWM")
        self.lineEdit_Speed = QtWidgets.QLineEdit(Form)
        self.lineEdit_Speed.setGeometry(QtCore.QRect(160, 240, 51, 20))
        self.lineEdit_Speed.setObjectName("lineEdit_Speed")
        self.pushButton_CLOSE = QtWidgets.QPushButton(Form)
        self.pushButton_CLOSE.setGeometry(QtCore.QRect(510, 30, 75, 23))
        self.pushButton_CLOSE.setObjectName("pushButton_CLOSE")
        self.label_PWM = QtWidgets.QLabel(Form)
        self.label_PWM.setGeometry(QtCore.QRect(470, 140, 51, 16))
        self.label_PWM.setObjectName("label_PWM")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_OPEN.setText(_translate("Form", "打开串口"))
        self.pushButton.setText(_translate("Form", "发送"))
        self.pushButton_CLOSE.setText(_translate("Form", "关闭串口"))
        self.label_PWM.setText(_translate("Form", "设置PWM:"))
